"""first migration.

Revision ID: b3d0b62c03c6
Revises:
Create Date: 2020-07-30 21:30:16.631702
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b3d0b62c03c6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=True),
        sa.Column("article_body", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_article_article_body"), "article", ["article_body"], unique=False
    )
    op.create_index(op.f("ix_article_title"), "article", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_article_title"), table_name="article")
    op.drop_index(op.f("ix_article_article_body"), table_name="article")
    op.drop_table("article")
    # ### end Alembic commands ###
